language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  on:
    tags: true
    repo: gampleman/quick_check.js
    all_branches: true
  api_key:
    secure: "ku1IfcN3/C1GLQ1fnxO9CriUjBUhUrIIMZo8zrnbR4Kq7r1fGaQ1FmaBprv8jO2jcllyVNCWTQ7Q6KFUVTAwyBRjxv9OlgyMMbjBmYfOKh65dlPHAmugJkCdgfVtdJwYcKziBjXaRZMqFqx7xehwMBeLedqe9ZxapaE/YkMkiNc="
  after_deploy: node_modules/.bin/grunt deploy
env:
  global:
    secure: JANv6IDJESWst8TflbgAn0YC0hNma0vj0Gf9/E9gjXg+JXFcJnhxtT1T6bGYp6elXd5I5KtI2IPGaQJP71HuqxmnEsd86MIpTclmtRDRjwfx7UoTrRrPE43YN3W9c6xsQRGN/teZQJ4c6SFCFQKtDlnK4UThkkgtBcD1WkBxlgw=
